DROP TABLE IF EXISTS episode_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS episode_guests;
DROP TABLE IF EXISTS guests;
DROP TABLE IF EXISTS episodes;
DROP TABLE IF EXISTS shows;
