ALTER TABLE guests ADD COLUMN company TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN podcast TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN twitter TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN instagram TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN linkedin TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN mastodon TEXT NOT NULL DEFAULT '';
ALTER TABLE guests ADD COLUMN image TEXT NOT NULL DEFAULT '';
